### ISSUE TITLE
Is Image Resolution a Key Factor?

### ISSUE THREAD

**Issue by jiazhen-code** [QwenLM/Qwen-VL#25]
Thank you for the outstanding work. I would like to understand the reasons behind the exceptional performance of the model. Do you think it's related to the resolution? The resolution of mplug-doc is 1024, while yours is only 448, yet you achieved better performance than mplug-doc on docvqa. Additionally, I noticed that your adapter uses a query quantity of 256. Is this query quantity also a crucial factor?

I look forward to your response!

**Comment by ShuaiBai623** [comment]
1. Higher resolution is important for more detailed information extraction, especially for content with dense text and small fonts.
2. There are many factors for us to achieve better performance at smaller resolutions, such as the basic LLM model, training method, training data, etc.
3. We use a query quantity of 256, which can retain more information than 32. I also try a longer length such as 1024, which will cause a certain degree of convergence difficulty

**Comment by joaopedrosdmm** [comment]
> We use a query quantity of 256, which can retain more information than 32. I also try a longer length such as 1024, which will cause a certain degree of convergence difficulty

On the Blip2 paper they wrote they use a smaller query, 32, because it will retrieve the most important information, and leave out the irrelevant information. 

You say you use 256, because it will retain more information, but is the information retained any good? I mean is it worth it? to have a higher query. What test did you come up with to test this assumption?
